#index:
#    path: /
#    controller: App\Controller\DefaultController::index
loginPath: 
  path: /login
  controller: App\Controller\LoginController::template
logoutPath:
  path: /logout
  controller : App\Controller\LogOutController::logOut
registerPath:
  path: /register
  controller: App\Controller\RegisterController::template
homePath:
  path: /home
  controller: App\Controller\HomeController::home
adminPath:
  path: /admin
  controller : App\Controller\AdminController::admin