#index:
#    path: /
#    controller: App\Controller\DefaultController::index
loginPath: 
  path: /login
  controller: App\Controller\LoginController::template
logoutPath:
  path: /logout
  controller : App\Controller\LogOutController::logOut
registerPath:
  path: /register
  controller: App\Controller\RegisterController::template
homePath:
  path: /home
  controller: App\Controller\HomeController::home
adminPath:
  path: /admin
  controller : App\Controller\AdminController::admin

controllers:
    resource:
        path: '../src/Controller/'
        namespace: App\Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'